FROM node:20-alpine AS builder

WORKDIR /app

COPY apps/web/package*.json ./apps/web/
COPY packages/shared/package*.json ./packages/shared/

WORKDIR /app/packages/shared
RUN npm install

WORKDIR /app/apps/web
RUN npm install

WORKDIR /app
COPY packages/shared ./packages/shared
COPY apps/web ./apps/web

WORKDIR /app/apps/web
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html
EXPOSE 3000
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
